### ISSUE TITLE
CollectionView Support

### ISSUE THREAD

**Issue by conor-codes** [HorusSoftwareUY/Xamarin.Forms.Skeleton#15]
Does skeleton support collection views?

**Comment by codebreakerlegend2019** [comment]
I Cloned the sample and just change the listview to collection view. And it does works

**Comment by conor-codes** [comment]
I didn't end up using skeleton but I think the issue I was facing was trying to show the animation for data that was loaded from an API request. Every attempt I tried just seemed to fail.

**Comment by seba47** [comment]
@conor-codes yes, it does. As @codebreakerlegend2019 mentioned you could replace the control and it will work. Anyway we have uploaded a new page with a Collection View sample. Also, thanks for your clarification, maybe the problem was the API request. I will close the issue. Sorry for the delay.
