### ISSUE TITLE
Maui version

### ISSUE THREAD

**Issue by roubachof** [HorusSoftwareUY/Xamarin.Forms.Skeleton#28]
Helllooo guys !
I'm currently porting my https://github.com/roubachof/Sharpnado.TaskLoaderView to Maui, but my sample relies on your Skeleton package... I will be so happy if I could show skeleton loading with maui :)

**Comment by roubachof** [comment]
Just so you know, I will create a temporary nuget for the maui version.
And will retire it as soon as you publish your version :)

**Comment by fgiacomelli** [comment]
Hello, do you have any updates on this? If the package works on MAUI I'll be glad to use it :)

**Comment by roubachof** [comment]
What do you mean ? I posted this 3 days ago x)

**Comment by AgustinBonilla** [comment]
@roubachof Thank you for your support in adding MAUI to our Skeleton component. 

We are thrilled that this component has been helpful for your projects and we have now released the new NuGet package with full support for MAUI (https://www.nuget.org/packages/HorusStudio.Maui.Skeleton/). 

Please don't hesitate to let us know if there's anything else we can do! 

Thank you again!
