### ISSUE TITLE
Not working on first load

### ISSUE THREAD

**Issue by nakulLukan** [HorusSoftwareUY/Xamarin.Forms.Skeleton#5]
Hi,

_First of all, thanks a lot for saving our time by creating such a beautiful much required library._

The issue is animation is not working, even background color is not changing, when the page (A) is first loaded. When we push a page (B) and popping (B) will animate all loaders on main page (A).

Xamarin Forms:- 4.4
iOS sdk- 13.1
Android sdk- pie

**Comment by nakulLukan** [comment]
> 
> 
> Hi,
> 
> _First of all, thanks a lot for saving our time by creating such a beautiful much required library._
> 
> The issue is animation is not working, even background color is not changing, when the page (A) is first loaded. When we push a page (B) and popping (B) will animate all loaders on main page (A).
> 
> Xamarin Forms:- 4.4
> iOS sdk- 13.1
> Android sdk- pie

**Comment by nakulLukan** [comment]
The issue was from my side.

<Label Text={Binding StatusMessage} ...../>

Since the `StatusMessage` empty initially, the width label was zero, which did not show the effect.
Solved by setting `MinimumWidthRequest=50`

**Comment by AgustinBonilla** [comment]
Hi @nakulLukan, thanks for the feedback! We really appreciate it.
