### ISSUE TITLE
Open to custom animations

### ISSUE THREAD

**Issue by felipebaltazar** [HorusSoftwareUY/Xamarin.Forms.Skeleton#9]
## Overview

Would be cool the possibility to create custom animations and use them on `Skeleton`

## Details

**Skeleton** can use a `Type` parameter, instead of `enum`, to get the animation and build it dynamically
We can provide some static values, like `Label.FontSize` has the `Small` `Medium` and `Large` presets on Xamarin.Forms

```xaml
<StackLayout
             Padding="16"
             extension:Skeleton.IsParent="True"
             extension:Skeleton.IsBusy="{Binding IsBusy}"
             extension:Skeleton.Animation="local:MyCustomAnimation">
```

**Comment by AgustinBonilla** [comment]
Hi @felipebaltazar , this idea looks awesome! If you want it and have free time you can create another PR and we include it in the next version. We really appreciate your feedback!!
